#!/usr/bin/env python3
"""
Génère wahwah_coeff_rom.vhd — ROM de coefficients biquad pour le wah-wah.

Pour chaque position du LFO (0..255), on pré-calcule :
  - Le signal de contrôle sinusoidal (0..1)
  - La fréquence centrale fc via balayage exponentiel
  - Les coefficients RBJ bandpass constant 0 dB peak gain
  - Stockage en virgule fixe Q1.14 (signed 16 bits)

Coefficients stockés : b0, neg_a1 (= -a1), neg_a2 (= -a2)
b1 = 0 et b2 = -b0 sont déduits en matériel sans stockage supplémentaire.

Usage:
    python generate_wahwah_rom.py
"""

import math
import pathlib

# ── Paramètres DSP ──────────────────────────────────────────────────────────
FS        = 48000.0   # Fréquence d'échantillonnage I2S (Nexys Video)
Q         = 0.8       # Facteur de qualité du passe-bande (très large)
FMIN      = 400.0     # Fréquence basse du sweep (Hz)
FMAX      = 2200.0    # Fréquence haute du sweep (Hz)
N_LUT     = 256       # Nombre d'entrées dans la ROM (8-bit d'adresse)
FRAC_BITS = 14        # Bits fractionnaires du format Q1.14


def compute_coefficients():
    """Retourne trois listes de N_LUT entiers signés Q1.14 : b0, neg_a1, neg_a2."""
    b0_list     = []
    neg_a1_list = []
    neg_a2_list = []

    for i in range(N_LUT):
        # Signal de contrôle sinusoïdal [0, 1]
        phase   = 2.0 * math.pi * i / N_LUT
        control = 0.5 * (1.0 + math.sin(phase))

        # Balayage exponentiel de la fréquence centrale
        fc = FMIN * (FMAX / FMIN) ** control

        # Coefficients RBJ — Bandpass (constant 0 dB peak gain)
        w0    = 2.0 * math.pi * fc / FS
        alpha = math.sin(w0) / (2.0 * Q)
        a0    = 1.0 + alpha

        b0     =  alpha          / a0
        a1     = -2.0 * math.cos(w0) / a0
        a2     =  (1.0 - alpha)  / a0

        scale = 1 << FRAC_BITS
        b0_list.append(int(round(b0 * scale)))
        neg_a1_list.append(int(round(-a1 * scale)))   # stocke -a1 (positif, ~+1.9)
        neg_a2_list.append(int(round(-a2 * scale)))    # stocke -a2 (négatif, ~-0.97)

    return b0_list, neg_a1_list, neg_a2_list


def generate_vhdl(b0, neg_a1, neg_a2) -> str:
    """Génère le code source VHDL complet de la ROM."""
    lines = []
    lines.append("-- ==========================================================================")
    lines.append("-- wahwah_coeff_rom.vhd — ROM de coefficients biquad pour le wah-wah")
    lines.append("-- AUTO-GENERATED by generate_wahwah_rom.py — NE PAS EDITER MANUELLEMENT")
    lines.append(f"-- Params: fs={FS}, Q={Q}, fmin={FMIN}, fmax={FMAX}, frac_bits={FRAC_BITS}")
    lines.append("-- Format: signed 16 bits, Q1.14 (plage [-2.0, +1.99994])")
    lines.append("-- ==========================================================================")
    lines.append("")
    lines.append("library ieee;")
    lines.append("use ieee.std_logic_1164.all;")
    lines.append("use ieee.numeric_std.all;")
    lines.append("")
    lines.append("entity wahwah_coeff_rom is")
    lines.append("  port (")
    lines.append("    I_address : in  std_logic_vector(7 downto 0);  -- LFO phase index (0..255)")
    lines.append("    O_b0     : out signed(15 downto 0);            -- coefficient b0   (Q1.14)")
    lines.append("    O_neg_a1 : out signed(15 downto 0);            -- coefficient -a1  (Q1.14)")
    lines.append("    O_neg_a2 : out signed(15 downto 0)             -- coefficient -a2  (Q1.14)")
    lines.append("  );")
    lines.append("end entity wahwah_coeff_rom;")
    lines.append("")
    lines.append("architecture rom_arch of wahwah_coeff_rom is")
    lines.append("")
    lines.append("  type coeff_rom_t is array(0 to 255) of signed(15 downto 0);")
    lines.append("")

    def emit_array(name, vals):
        lines.append(f"  constant {name} : coeff_rom_t := (")
        for j, v in enumerate(vals):
            comma = "," if j < len(vals) - 1 else " "
            lines.append(f"    to_signed({v:6d}, 16){comma} -- [{j}]")
        lines.append("  );")
        lines.append("")

    emit_array("B0_ROM",     b0)
    emit_array("NEG_A1_ROM", neg_a1)
    emit_array("NEG_A2_ROM", neg_a2)

    lines.append("begin")
    lines.append("")
    lines.append("  -- Lecture combinatoire (pas de registre de sortie)")
    lines.append("  O_b0     <= B0_ROM    (to_integer(unsigned(I_address)));")
    lines.append("  O_neg_a1 <= NEG_A1_ROM(to_integer(unsigned(I_address)));")
    lines.append("  O_neg_a2 <= NEG_A2_ROM(to_integer(unsigned(I_address)));")
    lines.append("")
    lines.append("end architecture rom_arch;")

    return "\n".join(lines) + "\n"


def main():
    b0, neg_a1, neg_a2 = compute_coefficients()
    vhdl = generate_vhdl(b0, neg_a1, neg_a2)

    hdl_dir = pathlib.Path(__file__).resolve().parent / "src" / "hdl"
    out_path = hdl_dir / "wahwah_coeff_rom.vhd"
    out_path.write_text(vhdl)
    print(f"Généré : {out_path}  ({N_LUT} entrées, Q1.{FRAC_BITS})")


if __name__ == "__main__":
    main()
